name: Update Readme with Dev Metrics

on:
  schedule:
    # runs at 8 AM UTC every day (0:00 AM UTC+8)
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Dev Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          COMMIT_MESSAGE: "chore: Update README with Dev Metrics"
